version: "3"

services:
  company-web: 
    image: hub.c.163.com/xychenli/php5:develop
    ports:
         - "80:80"
    networks:
         - company-bridge
    links:
      - company-redis
      - company-mysql
    volumes:
         - /Users/chen/data/www:/var/www:cached
         - ./conf.d:/etc/nginx/conf.d:cached

  company-redis:
    image: redis
    networks:
        - company-bridge

  company-mysql:
    image: mysql:5.6
    ports:
         - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - company-bridge

networks:
    company-bridge:
        driver: bridge
volumes:
  mysql-data:
